### ISSUE TITLE
ReferenceError: btoa is not defined (during SSR)

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#101]
## What:

Performing SSR with `atomic-layout` results into the following exception:

```
ReferenceError: btoa is not defined
    at /Users/azakharchenko/projects/pwa/node_modules/atomic-layout/lib/index.js:1224:3
    at /Users/azakharchenko/projects/pwa/node_modules/atomic-layout/lib/index.js:670:29
    at /Users/azakharchenko/projects/pwa/node_modules/atomic-layout/lib/index.js:263:14
    at Composition (/Users/azakharchenko/projects/pwa/node_modules/atomic-layout/lib/index.js:1264:24)
    at processChild (/Users/azakharchenko/projects/pwa/node_modules/react-dom/cjs/react-dom-server.node.development.js:2868:14)
    at resolve (/Users/azakharchenko/projects/pwa/node_modules/react-dom/cjs/react-dom-server.node.development.js:2792:5)
    at ReactDOMServerRenderer.render (/Users/azakharchenko/projects/pwa/node_modules/react-dom/cjs/react-dom-server.node.development.js:3172:22)
    at ReactDOMServerRenderer.read (/Users/azakharchenko/projects/pwa/node_modules/react-dom/cjs/react-dom-server.node.development.js:3131:29)
    at renderToString (/Users/azakharchenko/projects/pwa/node_modules/react-dom/cjs/react-dom-server.node.development.js:3598:27)
    at app.get (webpack:///./src/server/middleware/ssr/index.js?:42:96)
```

## Why:

I believe `btoa` is a `window` method, and is not available on the client-side.

## Environment:

- atomic-layout version: `0.6.0`

## Expected behavior:

Atomic layout doesn't result into errors during SSR of an application.

## Suggestions

Replace `btoa` with a lightweight hash generator package (or write your own in the sources)

**Comment by lokhmakov** [comment]
@kettanaito 

### What:

In NextJS the same:

```
ReferenceError: btoa is not defined
    at /Users/lokhmakov/dev/evoke-me/frontend/node_modules/atomic-layout/lib/index.js:1224:3
    at /Users/lokhmakov/dev/evoke-me/frontend/node_modules/atomic-layout/lib/index.js:670:29
    at /Users/lokhmakov/dev/evoke-me/frontend/node_modules/atomic-layout/lib/index.js:263:14
    at Composition (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/atomic-layout/lib/index.js:1264:24)
    at processChild (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2868:14)
    at resolve (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2792:5)
    at ReactDOMServerRenderer.render (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3172:22)
    at ReactDOMServerRenderer.read (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3131:29)
    at renderToString (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3598:27)
    at renderPage (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/next/dist/server/render.js:319:26)
    at Function.getInitialProps (/Users/lokhmakov/dev/evoke-me/frontend/.next/server/static/development/pages/_document.js:178:18)
    at _callee$ (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/next/dist/lib/utils.js:86:30)
    at tryCatch (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
```

### Environment:

- atomic-layout: version 0.6.1

### Temporary solution:

```
if (typeof btoa === 'undefined') {
  global.btoa = function (str) {
    return new Buffer(str, 'binary').toString('base64')
  }
}
```

### Next error:

```
ReferenceError: window is not defined
    at generateComponents (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/atomic-layout/lib/index.js:1114:23)
    at /Users/lokhmakov/dev/evoke-me/frontend/node_modules/atomic-layout/lib/index.js:263:14
    at /Users/lokhmakov/dev/evoke-me/frontend/node_modules/atomic-layout/lib/index.js:673:27
    at /Users/lokhmakov/dev/evoke-me/frontend/node_modules/atomic-layout/lib/index.js:263:14
    at Composition (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/atomic-layout/lib/index.js:1264:24)
    at processChild (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2868:14)
    at resolve (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2792:5)
    at ReactDOMServerRenderer.render (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3172:22)
    at ReactDOMServerRenderer.read (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3131:29)
    at renderToString (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3598:27)
    at renderPage (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/next/dist/server/render.js:319:26)
    at Function.getInitialProps (/Users/lokhmakov/dev/evoke-me/frontend/.next/server/static/development/pages/_document.js:178:18)
    at _callee$ (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/next/dist/lib/utils.js:86:30)
    at tryCatch (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/lokhmakov/dev/evoke-me/frontend/node_modules/regenerator-runtime/runtime.js:114:21)
```

**Comment by kettanaito** [comment]
Thanks for double checking, @lokhmakov.
I already have the fix on my branch. Let me write a test and merge.

The `window` error is related to the safety check whether the `Proxy` is defined.

**Comment by kettanaito** [comment]
The usage of `Buffer` as a polyfill nearly doubles the library's size. This is simply unacceptable. I will find a different solution to keys memoization.

**Comment by lokhmakov** [comment]
@kettanaito May use this? http://www.webtoolkit.info/javascript_base64.html#.XGBj1-IzaL4

**Comment by kettanaito** [comment]
@lokhmakov I thought about using a more concise version:

https://github.com/kettanaito/atomic-layout/blob/302574a29c3c697acb8a65cbe1d1283583da85c2/src/utils/strings/hashString/hashString.ts#L1-L13

Does you think it would replace `btoa` nicely? It would be a numeric value now, opposed to a string, but it's reproducible and thus can be used in memoization.

**Comment by kettanaito** [comment]
The fix has been merged.

It would be nice to release it together with #100.

**Comment by lokhmakov** [comment]
> Does you think it would replace `btoa` nicely?

Yep, in case where u need only unique representation of string (`propName` + `templateAreas`) it will be normal! )

**Comment by lokhmakov** [comment]
@kettanaito But for SSR in code still `return !('Proxy' in window)`.

**Comment by kettanaito** [comment]
@lokhmakov You are right, thanks. Looks like I've lost one of my commits. Will merge soon.

**Comment by kettanaito** [comment]
Area components generation no longer relies on neither `Proxy` nor `window`.

https://github.com/kettanaito/atomic-layout/blob/f430d503901e8e9f3fb599e4563f232dbaf1b668/src/utils/templates/generateComponents/generateComponents.tsx#L86-L92

I need to mention somewhere that you need to make an explicit area component existence check prior to its rendering on the older browsers without Proxy support:

```jsx
<Composition template="area conditionalArea" templateMd="area">
{({ Area, ConditionalArea }) => (
  <>
    <Area />
    {ConditionalArea && <ConditionalArea />}
  </>
)
</Composition>
```
