### ISSUE TITLE
Flaky tests: useBreakpointChange

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#192]
I've experienced a set of flacky tests during this build. 

* [Build details](https://circleci.com/gh/kettanaito/atomic-layout/792)

Flacky tests:

```
1) Hooks useBreakpointChange Sets breakpoint name on breakpoint change:
     CypressError: Timed out retrying: expected '<p#call-count>' to have text '1', but the text was '2'
      at Object.cypressErr (http://localhost:43165/__cypress/runner/cypress_runner.js:65727:11)
      at Object.throwErr (http://localhost:43165/__cypress/runner/cypress_runner.js:65692:18)
      at Object.throwErrByPath (http://localhost:43165/__cypress/runner/cypress_runner.js:65719:17)
      at retry (http://localhost:43165/__cypress/runner/cypress_runner.js:59237:16)
      at http://localhost:43165/__cypress/runner/cypress_runner.js:51312:18
      at tryCatcher (http://localhost:43165/__cypress/runner/cypress_runner.js:131273:23)
      at Promise._settlePromiseFromHandler (http://localhost:43165/__cypress/runner/cypress_runner.js:129291:31)
      at Promise._settlePromise (http://localhost:43165/__cypress/runner/cypress_runner.js:129348:18)
      at Promise._settlePromise0 (http://localhost:43165/__cypress/runner/cypress_runner.js:129393:10)
      at Promise._settlePromises (http://localhost:43165/__cypress/runner/cypress_runner.js:129468:18)
      at Async._drainQueue (http://localhost:43165/__cypress/runner/cypress_runner.js:126197:16)
      at Async._drainQueues (http://localhost:43165/__cypress/runner/cypress_runner.js:126207:10)
      at Async.drainQueues (http://localhost:43165/__cypress/runner/cypress_runner.js:126081:14)

  2) Hooks useBreakpointChange Swallows resize within the same breakpoint:
     CypressError: Timed out retrying: expected '<p#call-count>' to have text '1', but the text was '2'
      at Object.cypressErr (http://localhost:43165/__cypress/runner/cypress_runner.js:65727:11)
      at Object.throwErr (http://localhost:43165/__cypress/runner/cypress_runner.js:65692:18)
      at Object.throwErrByPath (http://localhost:43165/__cypress/runner/cypress_runner.js:65719:17)
      at retry (http://localhost:43165/__cypress/runner/cypress_runner.js:59237:16)
      at http://localhost:43165/__cypress/runner/cypress_runner.js:51312:18
      at tryCatcher (http://localhost:43165/__cypress/runner/cypress_runner.js:131273:23)
      at Promise._settlePromiseFromHandler (http://localhost:43165/__cypress/runner/cypress_runner.js:129291:31)
      at Promise._settlePromise (http://localhost:43165/__cypress/runner/cypress_runner.js:129348:18)
      at Promise._settlePromise0 (http://localhost:43165/__cypress/runner/cypress_runner.js:129393:10)
      at Promise._settlePromises (http://localhost:43165/__cypress/runner/cypress_runner.js:129468:18)
      at Async._drainQueue (http://localhost:43165/__cypress/runner/cypress_runner.js:126197:16)
      at Async._drainQueues (http://localhost:43165/__cypress/runner/cypress_runner.js:126207:10)
      at Async.drainQueues (http://localhost:43165/__cypress/runner/cypress_runner.js:126081:14)

  3) Hooks useBreakpointChange re-renders on breakpoint change:
     CypressError: Timed out retrying: expected '<p#call-count>' to have text '2', but the text was '3'
      at Object.cypressErr (http://localhost:43165/__cypress/runner/cypress_runner.js:65727:11)
      at Object.throwErr (http://localhost:43165/__cypress/runner/cypress_runner.js:65692:18)
      at Object.throwErrByPath (http://localhost:43165/__cypress/runner/cypress_runner.js:65719:17)
      at retry (http://localhost:43165/__cypress/runner/cypress_runner.js:59237:16)
      at http://localhost:43165/__cypress/runner/cypress_runner.js:51312:18
      at tryCatcher (http://localhost:43165/__cypress/runner/cypress_runner.js:131273:23)
      at Promise._settlePromiseFromHandler (http://localhost:43165/__cypress/runner/cypress_runner.js:129291:31)
      at Promise._settlePromise (http://localhost:43165/__cypress/runner/cypress_runner.js:129348:18)
      at Promise._settlePromise0 (http://localhost:43165/__cypress/runner/cypress_runner.js:129393:10)
      at Promise._settlePromises (http://localhost:43165/__cypress/runner/cypress_runner.js:129468:18)
      at Async._drainQueue (http://localhost:43165/__cypress/runner/cypress_runner.js:126197:16)
      at Async._drainQueues (http://localhost:43165/__cypress/runner/cypress_runner.js:126207:10)
      at Async.drainQueues (http://localhost:43165/__cypress/runner/cypress_runner.js:126081:14)
```

Restarting the test job resolved the issue, but this must be taken into account. If these tests keep to fail an issue must be created and they must be adjusted.

**Comment by kettanaito** [comment]
This may have to do with the "jumping" behavior of responsive values in hooks. When I load the stories locally I always see the initial value jumping to the actual value in a matter of a second. That second may be enough for Cypress to validate an assertion as invalid and move on.

**Comment by kettanaito** [comment]
I've removed call count assertion from E2E tests in #230, so this issue should be gone. Needs to be observed (I suggest running the flaky test a large amount of time to confirm it passes), and closed, if no longer reproducible.

**Comment by kettanaito** [comment]
Switching to verify the flaky test...

**Comment by kettanaito** [comment]
After 100x test runs of the flacky test it has passed all the time. I believe the mentioned pull request has fixed the issue.
