### ISSUE TITLE
ESM module cannot bundle in "development" environment

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#200]
## What:

When performed the following command:

```bash
node_modules/.bin/rollup -c --environment TARGET:esm
```

I get the error:

```
src/index.ts → esm/index.js...
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
src/utils/templates/generateComponents/generateComponents.tsx: (52:21)
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/utils/templates/generateComponents/generateComponents.tsx (52:21)
50: const createAreaComponent = (areaName: string): AreaComponent => (props) => (
51:   <Box area={areaName} {...props} />
52: )
     ^
53: 
54: /**
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/Users/kettanaito/Projects/atomic-layout/node_modules/rollup/dist/rollup.js:9402:30)
    at Module.error (/Users/kettanaito/Projects/atomic-layout/node_modules/rollup/dist/rollup.js:13341:9)
    at tryParse (/Users/kettanaito/Projects/atomic-layout/node_modules/rollup/dist/rollup.js:13256:16)
    at Module.setSource (/Users/kettanaito/Projects/atomic-layout/node_modules/rollup/dist/rollup.js:13567:33)
    at Promise.resolve.catch.then.then.then (/Users/kettanaito/Projects/atomic-layout/node_modules/rollup/dist/rollup.js:16370:20)
```

## Why:

It looks like TypeScript compilation doesn't happen for some reason when running in "development" mode.

## Environment:

- atomic-layout version: `0.9.1`

**Comment by kettanaito** [comment]
The previous error has been related to the absence of Babel transformation during the build (2c18dafcd3f7bfafa24e72b42c69e7273a3fce2f). Now there is a different one:

```
src/index.ts → esm/index.js...
[!] (plugin babel) SyntaxError: /Users/kettanaito/Projects/atomic-layout/src/utils/templates/generateComponents/generateComponents.tsx: Unexpected token (52:21)

  50 |                 }
  51 |                 // @ts-ignore-line
> 52 |                 if (!) {
     |                      ^
  53 |                     console.warn('Prevented render of the area "%s", which is not found in the template definition. Please render one of the existing areas ("%s"), or modify the template to include "%s".', areaName, areas
  54 |                         /* Filter out "." placeholder from the list of areas */
  55 |                         .filter((singleAreaName) => /\w+/.test(singleAreaName))
src/utils/templates/generateComponents/generateComponents.tsx (52:21)
SyntaxError: /Users/kettanaito/Projects/atomic-layout/src/utils/templates/generateComponents/generateComponents.tsx: Unexpected token (52:21)

  50 |                 }
  51 |                 // @ts-ignore-line
> 52 |                 if (!) {
     |                      ^
  53 |                     console.warn('Prevented render of the area "%s", which is not found in the template definition. Please render one of the existing areas ("%s"), or modify the template to include "%s".', areaName, areas
  54 |                         /* Filter out "." placeholder from the list of areas */
  55 |                         .filter((singleAreaName) => /\w+/.test(singleAreaName))
    at Object.raise (/Users/kettanaito/Projects/atomic-layout/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6325:17)
    at Object.unexpected (/Users/kettanaito/Projects/atomic-layout/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7642:16)
    at Object.parseExprAtom (/Users/kettanaito/Projects/atomic-layout/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8841:20)
    at Object.parseExprAtom (/Users/kettanaito/Projects/atomic-layout/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:3601:20)
    at Object.parseExprSubscripts (/Users/kettanaito/Projects/atomic-layout/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8412:23)
    at Object.parseMaybeUnary (/Users/kettanaito/Projects/atomic-layout/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8392:21)
    at Object.parseMaybeUnary (/Users/kettanaito/Projects/atomic-layout/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5648:20)
    at Object.parseMaybeUnary (/Users/kettanaito/Projects/atomic-layout/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8369:28)
    at Object.parseMaybeUnary (/Users/kettanaito/Projects/atomic-layout/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5648:20)
    at Object.parseExprOps (/Users/kettanaito/Projects/atomic-layout/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8267:23)
```

**Comment by kettanaito** [comment]
Fixed by properly replacing the `__PROD__` environment variable with an empty string (6402902).
